### PR TITLE
Fix system_get_status stat2 chip mode return

### PR DESCRIPTION
**Pull request by ghost**
According to the official documentation (see references) of the LR1110 LoraWAN/Wi-Fi chip, the Stat2 register consists of the following:
```
------------------------------------------
|     [7:4]    |    [3:1]   |     [0]    |
------------------------------------------
| Reset status | Chip mode  | Bootloader |
------------------------------------------
```
However, when the chip_mode field in stat2 is assigned, the entire upper value (0xFE), shifted one bit right is taken:

`stat2->chip_mode = (cbuffer[1] >> 1);`

Because of this we also read the 'Reset status' bits, giving us a wrong 'Chip mode' value if the device was reset beforehand.

In order to match the documentation, the code should first select the chip_mode bits and then shift the value to the right:

`stat2->chip_mode = ((cbuffer[1] & 0x0F) >> 1);`

----

It might also be a good idea to create an additional field in`lr1110_system_stat2_t` called `reset_status` and assign the upper 4 bits to it:

`stat2->reset_status = ((cbuffer[1] & 0xF0) >> 4);`

Though I will leave this for you guys to decide. This currently does not impact my work at all.

References:

1. LR1110 User Manual Rev.1.0 March 2020 § 3.3.2.

### CODE REVIEW

**Comment by matthieuantoine** [comment]
Thanks a lot for reporting this!

We do not accept merge request but we will integrate the fix in the next release.

**Comment by ghost** [comment]
When would we be able to expect a new release?

We can probably provide other bug fixes, is there a medium where we could directly reach the developers for the issues that we face?

I can redo the merge request to meet your standards if required.

**Comment by matthieuantoine** [comment]
A major release is planned before end of september.

I'm one of the developers so I think this medium is OK to discuss!

Concerning the merge request, it is not an issue related to the way you developed it: we do not use Github as a development platform.

**Comment by ghost** [comment]
@matthieuantoine Thanks for the reply.

I understand that this is likely a 'mirror' of the actual repository, though it is a very convenient medium for me to propose bug fixes that we find. If you want us to continue the discussion in Lora-Developers - that is fine with me too.

**Comment by matthieuantoine** [comment]
This is now solved in release v3.0.0. Thanks again for your sharp eye on this driver!

**Pull request closed without merging**
